// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPsuT6r4tJpZOM0Z9_siNH0jqUo-hZFgQ',
    appId: '1:644997878083:web:4231c45402cd04b7735ff6',
    messagingSenderId: '644997878083',
    projectId: 'milgaya-app-2026',
    authDomain: 'milgaya-app-2026.firebaseapp.com',
    storageBucket: 'milgaya-app-2026.firebasestorage.app',
    measurementId: 'G-VX07Q09GLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbX-LmCgX-FRQSGyeCIuKhQUoUujl_4rM',
    appId: '1:644997878083:android:33bcf4acb32520bb735ff6',
    messagingSenderId: '644997878083',
    projectId: 'milgaya-app-2026',
    storageBucket: 'milgaya-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W2rVexBRSt8yWm9qvRFPuEyDMS1hsu0',
    appId: '1:644997878083:ios:0e29fdf23290cdea735ff6',
    messagingSenderId: '644997878083',
    projectId: 'milgaya-app-2026',
    storageBucket: 'milgaya-app-2026.firebasestorage.app',
    iosClientId: '644997878083-patnlmfc82ja9ijkmom7nr9dc94fulc2.apps.googleusercontent.com',
    iosBundleId: 'com.milgaya.milgaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W2rVexBRSt8yWm9qvRFPuEyDMS1hsu0',
    appId: '1:644997878083:ios:0e29fdf23290cdea735ff6',
    messagingSenderId: '644997878083',
    projectId: 'milgaya-app-2026',
    storageBucket: 'milgaya-app-2026.firebasestorage.app',
    iosClientId: '644997878083-patnlmfc82ja9ijkmom7nr9dc94fulc2.apps.googleusercontent.com',
    iosBundleId: 'com.milgaya.milgaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPsuT6r4tJpZOM0Z9_siNH0jqUo-hZFgQ',
    appId: '1:644997878083:web:7f842615131264e0735ff6',
    messagingSenderId: '644997878083',
    projectId: 'milgaya-app-2026',
    authDomain: 'milgaya-app-2026.firebaseapp.com',
    storageBucket: 'milgaya-app-2026.firebasestorage.app',
    measurementId: 'G-G7PRZJ1QZD',
  );
}
